name: wayos_clone
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  get_storage: ^2.1.1
  http: ^1.3.0
  flutter_svg: ^2.0.17
  loading_animation_widget: ^1.3.0
  crypto: ^3.0.6
  toastification: ^3.0.1
  device_preview: ^1.2.0
  cached_network_image: ^3.4.1
  riverpod: ^2.6.1
  flutter_html: ^3.0.0
  permission_handler: ^11.4.0
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  syncfusion_flutter_pdfviewer: ^29.1.35
  syncfusion_flutter_core: ^29.1.35
  printing: ^5.14.2
  camera: ^0.10.5
  camera_web: ^0.3.5
  image: ^4.1.7
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  flutter_widget_from_html: ^0.17.1
  web: ^1.1.1
  
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
